import { Injectable } from "@angular/core";

@Injectable()
export class AnswersService {
  constructor() {}

  firstPresidency = () => [
    // cspell:disable
    "Russell M. Nelson",
    "Dallin H. Oaks",
    "Henry B. Eyring"
    // cspell:enable
  ];

  apostles = () => [
    // cspell:disable
    "M. Russell Ballard",
    "Jeffrey R. Holland",
    "Dieter F. Uchtdorf",
    "David A. Bednar",
    "Quentin L. Cook",
    "D. Todd Christofferson",
    "Neil L. Andersen",
    "Ronald A. Rasband",
    "Gary E. Stevenson",
    "Dale G. Renlund",
    "Gerrit W. Gong",
    "Ulisses Soares"
    // cspell:enable
  ];

  seventies = () => [
    // cspell:disable
    "Marcos A. Aidukaitis",
    "Rubén V. Alliaud",
    "Jose L. Alonso",
    "Jorge M. Alvarado",
    "Ian S. Ardern",
    "Steven R. Bangerter",
    "W. Mark Bassett",
    "David S. Baxter",
    "Randall K. Bennett",
    "Hans T. Boom",
    "Shayne M. Bowen",
    "Mark A. Bragg",
    "L. Todd Budge",
    "Matthew L. Carpenter",
    "Yoon Hwan Choi",
    "Craig C. Christensen",
    "Weatherford T. Clayton",
    "Valeri V. Cordón",
    "J. Devn Cornish",
    "Joaquin E. Costa",
    "LeGrand R. Curtis Jr.",
    "Massimo De Feo",
    "Benjamin De Hoyos",
    "Edward Dube",
    "Kevin R. Duncan",
    "Timothy J. Dyches",
    "David F. Evans",
    "Enrique R. Falabella",
    "Randy D. Funk",
    "Eduardo Gavarret",
    "Jack N. Gerard",
    "Ricardo P. Giménez",
    "Taylor G. Godoy",
    "Christoffel Golden",
    "Walter F. González",
    "Brook P. Hales",
    "Kevin S. Hamilton",
    "Allen D. Haynie",
    "Mathias Held",
    "David P. Homer",
    "Paul V. Johnson",
    "Peter M. Johnson",
    "Larry S. Kacher",
    "Jörg Klebingat",
    "Joni L. Koch",
    "Erich W. Kopischke",
    "Hugo E. Martinez",
    "James B. Martino",
    "Richard J. Maynes",
    "John A. McCune",
    "Kyle S. McKay",
    "Peter F. Meurs",
    "Hugo Montoya",
    "Marcus B. Nash",
    "K. Brett Nattress",
    "S. Gifford Nielsen",
    "Brent H. Nielson",
    "Adrián Ochoa",
    "S. Mark Palmer",
    "Adilson de Paula Parrella",
    "Kevin W. Pearson",
    "Anthony D. Perkins",
    "Paul B. Pieper",
    "John C. Pingree Jr.",
    "Rafael E. Pino",
    "James R. Rasband",
    "Michael T. Ringwood",
    "Lynn G. Robbins",
    "Gary B. Sabin",
    "Evan A. Schmutz",
    "Joseph W. Sitati",
    "Vern P. Stanfill",
    "Benjamin M. Z. Tai",
    "Brian K. Taylor",
    "Michael John U. Teh",
    "Juan A. Uceda",
    "Arnulfo Valenzuela",
    "Juan Pablo Villar",
    "Takashi Wada",
    "Taniela B. Wakolo",
    "Alan R. Walker",
    "Scott D. Whiting",
    "Chi Hong (Sam) Wong",
    "Kazuhiko Yamashita",
    "Jorge F. Zeballos"
    // cspell:enable
  ];

  presidencyOfTheSeventy = () => [
    // cspell:disable
    "L. Whitney Clayton",
    "Patrick Kearon",
    "Carl B. Cook",
    "Robert C. Gay",
    "Terence M. Vinson",
    "José A. Teixeira",
    "Carlos A. Godoy"
    // cspell:enable
  ];

  presidingBishopric = () => [
    // cspell:disable
    "Gérald Caussé",
    "Dean M. Davies",
    "W. Christopher Waddell"
    // cspell:enable
  ];

  reliefSocietyPresidency = () => [
    // cspell:disable
    "Jean B. Bingham",
    "Sharon Eubank",
    "Reyna I. Aburto"
    // cspell:enable
  ];

  youngMenPresidency = () => [
    // cspell:disable
    "Stephen W. Owen",
    "Douglas D. Holmes",
    "M. Joseph Brough"
    // cspell:enable
  ];

  youngWomenPresidency = () => [
    // cspell:disable
    "Bonnie H. Cordon",
    "Michelle Craig",
    "Becky Craven"
    // cspell:enable
  ];

  sundaySchoolPresidency = () => [
    // cspell:disable
    "Mark L. Pace",
    "Milton Camargo",
    "Jan E. Newman"
    // cspell:enable
  ];

  primaryPresidency = () => [
    // cspell:disable
    "Joy D. Jones",
    "Lisa L. Harkness",
    "Cristina B. Franco"
    // cspell:enable
  ];

  hymnsAndSongs = () => [
    // cspell:disable
    "The Morning Breaks",
    "The Spirit of God",
    "Now Let Us Rejoice",
    "Truth Eternal",
    "High on the Mountain Top",
    "Redeemer of Israel",
    "Israel, Israel, God Is Calling",
    "Awake and Arise",
    "Come, Rejoice",
    "Come, Sing to the Lord",
    "What Was Witnessed in the Heavens?",
    "'Twas Witnessed in the Morning Sky",
    "An Angel from on High",
    "Sweet Is the Peace the Gospel Brings",
    "I Saw a Mighty Angel Fly",
    "What Glorious Scenes Mine Eyes Behold",
    "Awake, Ye Saints of God, Awake!",
    "The Voice of God Again Is Heard",
    "We Thank Thee, O God, for a Prophet",
    "God of Power, God of Right",
    "Come, Listen to a Prophet's Voice",
    "We Listen to a Prophet's Voice",
    "We Ever Pray for Thee",
    "God Bless Our Prophet Dear",
    "Now We'll Sing with One Accord",
    "Joseph Smith's First Prayer",
    "Praise to the Man",
    "Saints, Behold How Great Jehovah",
    "A Poor Wayfaring Man of Grief",
    "Come, Come, Ye Saints",
    "O God, Our Help in Ages Past",
    "The Happy Day at Last Has Come",
    "Our Mountain Home So Dear",
    "O Ye Mountains High",
    "For the Strength of the Hills",
    "They, the Builders of the Nation",
    "The Wintry Day, Descending to Its Close",
    "Come, All Ye Saints of Zion",
    "O Saints of Zion",
    "Arise, O Glorious Zion",
    "Let Zion in Her Beauty Rise",
    "Hail to the Brightness of Zion's Glad Morning!",
    "Zion Stands with Hills Surrounded",
    "Beautiful Zion, Built Above",
    "Lead Me into Life Eternal",
    "Glorious Things of Thee Are Spoken",
    "We Will Sing of Zion",
    "Glorious Things Are Sung of Zion",
    "Adam-ondi-Ahman",
    "Come, Thou Glorious Day of Promise",
    "Sons of Michael, He Approaches",
    "The Day Dawn Is Breaking",
    "Let Earth's Inhabitants Rejoice",
    "Behold, the Mountain of the Lord",
    "Lo, the Mighty God Appearing!",
    "Softly Beams the Sacred Dawning",
    "We're Not Ashamed to Own Our Lord",
    "Come, Ye Children of the Lord",
    "Come, O Thou King of Kings",
    "Battle Hymn of the Republic",
    "Raise Your Voices to the Lord",
    "All Creatures of Our God and King",
    "Great King of Heaven",
    "On This Day of Joy and Gladness",
    "Come, All Ye Saints Who Dwell on Earth",
    "Rejoice, the Lord Is King!",
    "Glory to God on High",
    "A Mighty Fortress Is Our God",
    "All Glory, Laud, and Honor",
    "Sing Praise to Him",
    "With Songs of Praise",
    "Praise to the Lord, the Almighty",
    "Praise the Lord with Heart and Voice",
    "Praise Ye the Lord",
    "In Hymns of Praise",
    "God of Our Fathers, We Come unto Thee",
    "Great Is the Lord",
    "God of Our Fathers, Whose Almighty Hand",
    "With All the Power of Heart and Tongue",
    "God of Our Fathers, Known of Old",
    "Press Forward, Saints",
    "For All the Saints",
    "Guide Us, O Thou Great Jehovah",
    "Faith of Our Fathers",
    "How Firm a Foundation",
    "How Great Thou Art",
    "God Is Love",
    "Great God, Attend While Zion Sings",
    "The Lord Is My Light",
    "From All That Dwell below the Skies",
    "Father, Thy Children to Thee Now Raise",
    "For the Beauty of the Earth",
    "Prayer of Thanksgiving",
    "Come, Ye Thankful People",
    "Now Thank We All Our God",
    "Dearest Children, God Is Near You",
    "Lead, Kindly Light",
    "I Need Thee Every Hour",
    "Nearer, Dear Savior, to Thee",
    "Nearer, My God, to Thee",
    "Guide Me to Thee",
    "Jesus, Lover of My Soul",
    "Precious Savior, Dear Redeemer",
    "Jesus, Savior, Pilot Me",
    "Master, the Tempest Is Raging",
    "God Speed the Right",
    "Lord, Accept Our True Devotion",
    "The Lord Is My Shepherd",
    "The Lord My Pasture Will Prepare",
    "Cast Thy Burden upon the Lord",
    "Rock of Ages",
    "Savior, Redeemer of My Soul",
    "Our Savior's Love",
    "Come unto Him",
    "Come, Ye Disconsolate",
    "Come, Follow Me",
    "Come unto Jesus",
    "Ye Simple Souls Who Stray",
    "Come, We That Love the Lord",
    "Lean on My Ample Arm",
    "I'm a Pilgrim, I'm a Stranger",
    "Though Deepening Trials",
    "Oh, May My Soul Commune with Thee",
    "Be Still, My Soul",
    "How Gentle God's Commands",
    "How Long, O Lord Most Holy and True",
    "Does the Journey Seem Long?",
    "When Faith Endures",
    "Where Can I Turn for Peace?",
    "Be Thou Humble",
    "More Holiness Give Me",
    "God Is in His Holy Temple",
    "Father in Heaven",
    "I Believe in Christ",
    "My Redeemer Lives",
    "I Know That My Redeemer Lives",
    "Testimony",
    "Bless Our Fast, We Pray",
    "In Fasting We Approach Thee",
    "Did You Think to Pray?",
    "Jesus, the Very Thought of Thee",
    "Sweet Hour of Prayer",
    "Let the Holy Spirit Guide",
    "Secret Prayer",
    "Prayer Is the Soul's Sincere Desire",
    "Gently Raise the Sacred Strain",
    "Sweet Is the Work",
    "Sabbath Day",
    "As the Dew from Heaven Distilling",
    "O Thou Kind and Gracious Father",
    "We Meet, Dear Lord",
    "God Be with You Till We Meet Again",
    "Lord, We Ask Thee Ere We Part",
    "Father, This Hour Has Been One of Joy",
    "We Have Partaken of Thy Love",
    "Sing We Now at Parting",
    "Thy Spirit, Lord, Has Stirred Our Souls",
    "Before Thee, Lord, I Bow My Head",
    "Now the Day Is Over",
    "Softly Now the Light of Day",
    "The Lord Be with Us",
    "Lord, We Come before Thee Now",
    "Lord, Dismiss Us with Thy Blessing",
    "Great God, to Thee My Evening Song",
    "Abide with Me; 'Tis Eventide",
    "Abide with Me!",
    "Come, Let Us Sing an Evening Hymn",
    "As the Shadows Fall",
    "As Now We Take the Sacrament",
    "God, Our Father, Hear Us Pray",
    "With Humble Heart",
    "In Humility, Our Savior",
    "While of These Emblems We Partake",
    "While of These Emblems We Partake",
    "O God, the Eternal Father",
    "'Tis Sweet to Sing the Matchless Love",
    "'Tis Sweet To Sing the Matchless Love",
    "O Lord of Hosts",
    "Again, Our Dear Redeeming Lord",
    "Father in Heaven, We Do Believe",
    "Jesus of Nazareth, Savior and King",
    "We'll Sing All Hail to Jesus' Name",
    "In Remembrance of Thy Suffering",
    "Upon the Cross of Calvary",
    "Reverently and Meekly Now",
    "Again We Meet around the Board",
    "God Loved Us, So He Sent His Son",
    "Thy Will, O Lord, Be Done",
    "O Thou, Before the World Began",
    "In Memory of the Crucified",
    "Behold the Great Redeemer Die",
    "He Died! The Great Redeemer Died",
    "I Stand All Amazed",
    "There Is a Green Hill Far Away",
    "How Great the Wisdom and the Love",
    "Jesus, Once of Humble Birth",
    "O Savior, Thou Who Wearest a Crown",
    "That Easter Morn",
    "He Is Risen!",
    "Christ the Lord Is Risen Today",
    "Joy to the World",
    "Oh, Come, All Ye Faithful",
    "Angels We Have Heard on High",
    "Silent Night",
    "Once in Royal David's City",
    "Away in a Manger",
    "It Came upon the Midnight Clear",
    "O Little Town of Bethlehem",
    "Hark! The Herald Angels Sing",
    "With Wondering Awe",
    "While Shepherds Watched Their Flocks",
    "Far, Far Away on Judea's Plains",
    "The First Noel",
    "I Heard the Bells on Christmas Day",
    "Ring Out, Wild Bells",
    "We Are Sowing",
    "Come, Let Us Anew",
    "We Give Thee But Thine Own",
    "Because I Have Been Given Much",
    "Lord, I Would Follow Thee",
    "Dear to the Heart of the Shepherd",
    "Hear Thou Our Hymn, O Lord",
    "Have I Done Any Good?",
    "I Have Work Enough to Do",
    "We Are Marching On to Glory",
    "Improve the Shining Moments",
    "There Is Sunshine in My Soul Today",
    "You Can Make the Pathway Bright",
    "Today, While the Sun Shines",
    "Scatter Sunshine",
    "Father, Cheer Our Souls Tonight",
    "Let Us Oft Speak Kind Words",
    "Nay, Speak No Ill",
    "Jesus, Mighty King in Zion",
    "Should You Feel Inclined to Censure",
    "Lord, Accept into Thy Kingdom",
    "Do What Is Right",
    "Behold Thy Sons and Daughters, Lord",
    "Choose the Right",
    "Know This, That Every Soul Is Free",
    "Count Your Blessings",
    "Praise God, from Whom All Blessings Flow",
    "Let Us All Press On",
    "Come Along, Come Along",
    "This House We Dedicate to Thee",
    "Onward, Christian Soldiers",
    "We Love Thy House, O God",
    "Up, Awake, Ye Defenders of Zion",
    "Called to Serve",
    "We Are All Enlisted",
    "Behold! A Royal Army",
    "Put Your Shoulder to the Wheel",
    "Like Ten Thousand Legions Marching",
    "True to the Faith",
    "Carry On",
    "As Zion's Youth in Latter Days",
    "Rejoice! A Glorious Sound Is Heard",
    "O Thou Rock of Our Salvation",
    "Hope of Israel",
    "Who's on the Lord's Side?",
    "Thy Servants Are Prepared",
    "Go, Ye Messengers of Glory",
    "Go Forth with Faith",
    "Hark, All Ye Nations!",
    "Arise, O God, and Shine",
    "The Time Is Far Spent",
    "How Wondrous and Great",
    "Come, All Whose Souls Are Lighted",
    "Jehovah, Lord of Heaven and Earth",
    "I'll Go Where You Want Me to Go",
    "Oh, Holy Words of Truth and Love",
    "Oh Say, What Is Truth?",
    "Truth Reflects upon Our Senses",
    "The Iron Rod",
    "Men Are That They Might Have Joy",
    "Come Away to the Sunday School",
    "As I Search the Holy Scriptures",
    "Thanks for the Sabbath School",
    "Thy Holy Word",
    "Welcome, Welcome, Sabbath Morning",
    "Help Me Teach with Inspiration",
    "We Meet Again in Sabbath School",
    "The Glorious Gospel Light Has Shone",
    "If You Could Hie to Kolob",
    "God Moves in a Mysterious Way",
    "Oh, What Songs of the Heart",
    "Rise, Ye Saints, and Temples Enter",
    "How Beautiful Thy Temples, Lord",
    "Holy Temples on Mount Zion",
    "Rejoice, Ye Saints of Latter Days",
    "Turn Your Hearts",
    "O My Father",
    "Each Life That Touches Ours for Good",
    "Love at Home",
    "O Love That Glorifies the Son",
    "Our Father, by Whose Name",
    "From Homes of Saints Glad Songs Arise",
    "Home Can Be a Heaven on Earth",
    "Children of Our Heavenly Father",
    "Families Can Be Together Forever",
    "I Am a Child of God",
    "I Know My Father Lives",
    "Keep the Commandments",
    "Teach Me to Walk in the Light",
    "The Light Divine",
    "God's Daily Care",
    "In Our Lovely Deseret",
    "Love One Another",
    "As Sisters in Zion (Women)",
    "A Key Was Turned in Latter Days (Women)",
    "We Meet Again as Sisters (Women)",
    "We Ever Pray for Thee (Women)",
    "God Is Love (Women)",
    "How Gentle God's Commands (Women)",
    "Jesus, the Very Thought of Thee (Women)",
    "The Lord Is My Shepherd (Women)",
    "Sweet Is the Work (Women)",
    "Love at Home (Women)",
    "Ye Elders of Israel (Men)",
    "The Priesthood of Our Lord (Men)",
    "Ye Who Are Called to Labor (Men)",
    "Come, All Ye Sons of God (Men)",
    "Rise Up, O Men of God (Men's Choir)",
    "Rise Up, O Men of God (Men)",
    "See the Mighty Priesthood Gathered (Men's Choir)",
    "Come, Come, Ye Saints (Men's Choir)",
    "Go, Ye Messengers of Heaven (Men's Choir)",
    "An Angel from on High",
    "Thy Servants Are Prepared (Men's Choir)",
    "See, the Mighty Angel Flying (Men's Choir)",
    "Oh Say, What Is Truth? (Men's Choir)",
    "Come, O Thou King of Kings (Men's Choir)",
    "High on the Mountain Top (Men's Choir)",
    "I Need Thee Every Hour (Men's Choir)",
    "Brightly Beams Our Father's Mercy (Men's Choir)",
    "School Thy Feelings (Men's Choir)",
    "O Home Beloved (Men's Choir)",
    "America the Beautiful",
    "My Country, 'Tis of Thee",
    "The Star-Spangled Banner",
    "God Save the King",
    "I Am a Child of God",
    "I Lived in Heaven",
    "I Know My Father Lives",
    "Thanks to Thee",
    "I Thank Thee, Dear Father",
    "Father, We Thank Thee for the Night",
    "Can a Little Child like Me?",
    "Thank Thee for Everything",
    "I’m Thankful to Be Me",
    "A Child’s Prayer",
    "I Pray in Faith",
    "If with All Your Hearts",
    "Children All Over the World",
    "I Need My Heavenly Father",
    "Heavenly Father, Now I Pray",
    "A Song of Thanks",
    "Thanks to Our Father",
    "For Health and Strength",
    "For Thy Bounteous Blessings",
    "A Prayer Song",
    "A Prayer",
    "Father Up Above",
    "Heavenly Father, While I Pray",
    "Thank Thee, Father",
    "I Love to Pray",
    "We Bow Our Heads",
    "Reverently, Quietly",
    "Reverence",
    "We Are Reverent",
    "I Want to Be Reverent",
    "I Will Try to Be Reverent",
    "Father, I Will Reverent Be",
    "Our Chapel Is a Sacred Place",
    "This Is God’s House",
    "Reverence Is Love",
    "He Sent His Son",
    "Samuel Tells of the Baby Jesus",
    "Stars Were Gleaming",
    "When Joseph Went to Bethlehem",
    "Little Jesus",
    "The Shepherd’s Carol",
    "There Was Starlight on the Hillside",
    "Once within a Lowly Stable",
    "Away in a Manger",
    "Mary’s Lullaby",
    "Who Is the Child?",
    "Sleep, Little Jesus",
    "Oh, Hush Thee, My Baby",
    "Picture a Christmas",
    "Have a Very Merry Christmas!",
    "The Nativity Song",
    "Christmas Bells",
    "Jesus Once Was a Little Child",
    "I Think When I Read That Sweet Story",
    "Tell Me the Stories of Jesus",
    "Jesus Is Our Loving Friend",
    "Little Lambs So White and Fair",
    "Jesus Loved the Little Children",
    "Jesus Wants Me for a Sunbeam",
    "Jesus Said Love Everyone",
    "Beautiful Savior",
    "Did Jesus Really Live Again?",
    "He Died That We Might Live Again",
    "Hosanna",
    "Easter Hosanna",
    "Jesus Has Risen",
    "To Think about Jesus",
    "The Sacrament",
    "Before I Take the Sacrament",
    "Help Us, O God, to Understand",
    "I Feel My Savior’s Love",
    "This Is My Beloved Son",
    "The Church of Jesus Christ",
    "I’m Trying to Be like Jesus",
    "Had I Been a Child",
    "When He Comes Again",
    "An Angel Came to Joseph Smith",
    "The Golden Plates",
    "The Sacred Grove",
    "On a Golden Springtime",
    "The Priesthood Is Restored",
    "Truth from Elijah",
    "The Hearts of the Children",
    "Family History—I Am Doing It",
    "I Love to See the Temple",
    "Faith",
    "God’s Love",
    "Repentance",
    "Help Me, Dear Father",
    "Baptism",
    "When Jesus Christ Was Baptized",
    "When I Am Baptized",
    "I Like My Birthdays",
    "The Holy Ghost",
    "The Still Small Voice",
    "Listen, Listen",
    "Seek the Lord Early",
    "Search, Ponder, and Pray",
    "Follow the Prophet",
    "The Commandments",
    "The Books in the Old Testament",
    "The Books in the New Testament",
    "Book of Mormon Stories",
    "The Books in the Book of Mormon",
    "Nephi’s Courage",
    "The First Article of Faith",
    "The Second Article of Faith",
    "The Third Article of Faith",
    "The Fourth Article of Faith",
    "The Fifth Article of Faith",
    "The Seventh Article of Faith",
    "The Sixth Article of Faith",
    "The Eighth Article of Faith",
    "The Ninth Article of Faith",
    "The Tenth Article of Faith",
    "The Eleventh Article of Faith",
    "The Twelfth Article of Faith",
    "The Thirteenth Article of Faith",
    "Latter-day Prophets",
    "Our Bishop",
    "Love One Another",
    "Where Love Is",
    "I’ll Walk with You",
    "Every Star Is Different",
    "Shine On",
    "A Special Gift Is Kindness",
    "Kindness Begins with Me",
    "Keep the Commandments",
    "I Want to Live the Gospel",
    "I Believe in Being Honest",
    "I Want to Give the Lord My Tenth",
    "I’m Glad to Pay a Tithing",
    "I Am Glad for Many Things",
    "Hum Your Favorite Hymn",
    "The Lord Gave Me a Temple",
    "The Word of Wisdom",
    "Remember the Sabbath Day",
    "The Chapel Doors",
    "When I Go to Church",
    "Dare to Do Right",
    "Stand for the Right",
    "Choose the Right Way",
    "I Pledge Myself to Love the Right",
    "I Will Be Valiant",
    "I Am like a Star",
    "I Will Follow God’s Plan",
    "A Young Man Prepared",
    "Go the Second Mile",
    "I Want to Be a Missionary Now",
    "I Hope They Call Me on a Mission",
    "The Things I Do",
    "We’ll Bring the World His Truth",
    "Called to Serve",
    "Tell Me, Dear Lord",
    "Teach Me to Walk in the Light",
    "Teacher, Do You Love Me?",
    "How Dear to God Are Little Children",
    "How Will They Know?",
    "Families Can Be Together Forever",
    "Family Prayer",
    "Love Is Spoken Here",
    "Home",
    "Sing Your Way Home",
    "The Family",
    "Family Night",
    "Saturday",
    "A Happy Helper",
    "Quickly I’ll Obey",
    "A Happy Family",
    "When We’re Helping",
    "I Have a Family Tree",
    "Grandmother",
    "When Grandpa Comes*",
    "I Often Go Walking",
    "My Mother Dear",
    "Mother, Tell Me the Story",
    "Dearest Mother, I Love You",
    "Mother Dear",
    "Mother, I Love You",
    "The Dearest Names",
    "Fathers",
    "Daddy’s Homecoming",
    "My Dad",
    "Pioneer Children Sang As They Walked",
    "Pioneer Children Were Quick to Obey",
    "Little Pioneer Children",
    "Westward Ho!",
    "To Be a Pioneer",
    "The Oxcart",
    "The Handcart Song",
    "Covered Wagons",
    "Whenever I Think about Pioneers",
    "My Country",
    "My Flag, My Flag",
    "My Heavenly Father Loves Me",
    "God Is Watching Over All*",
    "I Think the World Is Glorious",
    "All Things Bright and Beautiful",
    "Beauty Everywhere",
    "The World Is So Lovely",
    "Because God Loves Me",
    "The World Is So Big",
    "“Give,” Said the Little Stream",
    "The Prophet Said to Plant a Garden",
    "Springtime Is Coming*",
    "Because It’s Spring",
    "In the Leafy Treetops",
    "Birds in the Tree",
    "Rain Is Falling All Around",
    "Popcorn Popping",
    "Little Seeds Lie Fast Asleep",
    "Little Purple Pansies",
    "Oh, What Do You Do in the Summertime?",
    "It’s Autumntime",
    "Autumn Day",
    "Falling Snow",
    "Once There Was a Snowman",
    "Lift Up Your Voice and Sing",
    "Fun to Do",
    "Sing a Song",
    "Hello, Friends!",
    "Our Door Is Always Open",
    "Come with Me to Primary",
    "We Welcome You",
    "Our Primary Colors",
    "We’re All Together Again",
    "Hello Song",
    "Here We Are Together",
    "Friends Are Fun",
    "We Are Different",
    "Happy Song",
    "Be Happy!*",
    "If You’re Happy",
    "A Smile Is like the Sunshine",
    "Smiles",
    "Two Little Eyes",
    "I Have Two Ears",
    "Two Happy Feet",
    "I Wiggle",
    "I Have Two Little Hands",
    "My Hands",
    "Roll Your Hands",
    "Head, Shoulders, Knees, and Toes",
    "To Get Quiet",
    "Do As I’m Doing",
    "Hinges",
    "Stand Up",
    "Oh, How We Love to Stand",
    "Healthy, Wealthy, and Wise",
    "The Wise Man and the Foolish Man",
    "Feliz Cumpleaños",
    "Your Happy Birthday",
    "Happy, Happy Birthday",
    "Have a Very Happy Birthday!",
    "You’ve Had a Birthday",
    "Impromptu",
    "To a Wild Rose",
    "Each Sunday Morning",
    "In Quietude",
    "Loving Shepherd",
    "Morning Prayer",
    "My Heart Ever Faithful",
    "Andante",
    "O Rest in the Lord",
    "Air from Orpheus",
    "Supplication",
    "Prelude in F",
    "Distant Bells"
    // cspell:enable
  ];

  colors = () => [
    "Red",
    "Orange",
    "Yellow",
    "Green",
    "Blue",
    "Purple",
    "Brown",
    "Magenta",
    "Tan",
    "Cyan",
    "Olive",
    "Maroon",
    "Navy",
    "Aquamarine",
    "Turquoise",
    "Silver",
    "Lime",
    "Teal",
    "Indigo",
    "Violet",
    "Pink",
    "Black",
    "White",
    "Gray"
  ];

  usaStates = () => [
    "Alabama",
    "Alaska",
    "American Samoa",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District Of Columbia",
    "Federated States Of Micronesia",
    "Florida",
    "Georgia",
    "Guam",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Marshall Islands",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Northern Mariana Islands",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Palau",
    "Pennsylvania",
    "Puerto Rico",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virgin Islands",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming"
  ];

  // Source: https://restcountries.eu/rest/v2/all
  countriesNotAmerica = () => [
    // cspell:disable
    "Afghanistan",
    "Åland Islands",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia (Plurinational State of)",
    "Bonaire, Sint Eustatius and Saba",
    "Bosnia and Herzegovina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "British Indian Ocean Territory",
    "United States Minor Outlying Islands",
    "Virgin Islands (British)",
    "Virgin Islands (U.S.)",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cabo Verde",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos (Keeling) Islands",
    "Colombia",
    "Comoros",
    "Congo",
    "Congo (Democratic Republic of the)",
    "Cook Islands",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Curaçao",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Falkland Islands (Malvinas)",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Heard Island and McDonald Islands",
    "Holy See",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Côte d'Ivoire",
    "Iran (Islamic Republic of)",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Lao People's Democratic Republic",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macao",
    "Macedonia (the former Yugoslav Republic of)",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia (Federated States of)",
    "Moldova (Republic of)",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "Korea (Democratic People's Republic of)",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine, State of",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Republic of Kosovo",
    "Réunion",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "Saint Barthélemy",
    "Saint Helena, Ascension and Tristan da Cunha",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Martin (French part)",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten (Dutch part)",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia and the South Sandwich Islands",
    "Korea (Republic of)",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Svalbard and Jan Mayen",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Taiwan",
    "Tajikistan",
    "Tanzania, United Republic of",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom of Great Britain and Northern Ireland",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela (Bolivarian Republic of)",
    "Viet Nam",
    "Wallis and Futuna",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe"
    // cspell:enable
  ];

  conferenceSessions = () => [
    "Saturday Morning Session",
    "Saturday Afternoon Session",
    "Bicentennial Special Session",
    "Sunday Morning Session",
    "Sunday Afternoon Session",
    "None"
  ];
}
