name: Additional Checks

on:
  push:
    branches:
      - master
jobs:
  owasp:
    name: OWASP
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "13"

      - name: Cache Gradle
        uses: actions/cache@v1
        env:
          cache-name: gradle-cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/*.gradle*') }}

      - name: Cache CVE Data
        uses: actions/cache@v1
        env:
          cache-name: cve
        with:
          path: ~/.gradle/dependency-check-data/
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('server/build.gradle') }}

      - name: Gradle Dependency Check Analyze
        working-directory: ./server
        run: ./gradlew dependencyCheckAnalyze

      - name: Gradle Dependency Updates Analyze
        working-directory: ./server
        run: ./gradlew checkDependencyUpdates

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: OWASP Files
          path: server/build/reports/
